# Generated by Django 4.0.4 on 2022-06-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='photos')),
                ('date', models.DateField()),
                ('posts', models.BooleanField(default=False)),
            ],
        ),
    ]
