# Generated by Django 4.0.4 on 2022-06-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='desc',
            field=models.TextField(default='Add something'),
        ),
    ]
